services:
  training:
    build: ./training
    container_name: training_service
    volumes:
      - model_artifacts:/artifacts

  forecasting-api:
    build: ./forecasting_service
    container_name: forecasting_api
    ports:
      - "8000:8000"
    volumes:
      - model_artifacts:/artifacts
    depends_on:
      training:
        condition: service_completed_successfully

  simulation-api:
    build: ./simulation_service
    container_name: simulation_api
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8501:8501"
    depends_on:
      - forecasting-api
      - simulation-api

volumes:
  model_artifacts: